2025-10-13 01:07:03 [ERROR]: Uncaught Exception:
{
  "service": "task-management-api",
  "error": {
    "message": "listen EADDRINUSE: address already in use :::5000",
    "stack": "Error: listen EADDRINUSE: address already in use :::5000\n    at Server.setupListenHandle [as _listen2] (node:net:1939:16)\n    at listenInCluster (node:net:1996:12)\n    at Server.listen (node:net:2101:7)\n    at Function.listen (D:\\Task\\enterprise-task-management\\backend\\node_modules\\express\\lib\\application.js:635:24)\n    at App.start (D:\\Task\\enterprise-task-management\\backend\\src\\app.ts:251:16)\n    at processTicksAndRejections (node:internal/process/task_queues:105:5)",
    "name": "Error"
  }
}
2025-10-13 01:07:24 [ERROR]: Uncaught Exception:
{
  "service": "task-management-api",
  "error": {
    "message": "listen EADDRINUSE: address already in use :::5000",
    "stack": "Error: listen EADDRINUSE: address already in use :::5000\n    at Server.setupListenHandle [as _listen2] (node:net:1939:16)\n    at listenInCluster (node:net:1996:12)\n    at Server.listen (node:net:2101:7)\n    at Function.listen (D:\\Task\\enterprise-task-management\\backend\\node_modules\\express\\lib\\application.js:635:24)\n    at App.start (D:\\Task\\enterprise-task-management\\backend\\src\\app.ts:251:16)\n    at processTicksAndRejections (node:internal/process/task_queues:105:5)",
    "name": "Error"
  }
}
2025-10-13 01:08:13 [ERROR]: Uncaught Exception:
{
  "service": "task-management-api",
  "error": {
    "message": "listen EADDRINUSE: address already in use :::5000",
    "stack": "Error: listen EADDRINUSE: address already in use :::5000\n    at Server.setupListenHandle [as _listen2] (node:net:1939:16)\n    at listenInCluster (node:net:1996:12)\n    at Server.listen (node:net:2101:7)\n    at Function.listen (D:\\Task\\enterprise-task-management\\backend\\node_modules\\express\\lib\\application.js:635:24)\n    at App.start (D:\\Task\\enterprise-task-management\\backend\\src\\app.ts:251:16)\n    at processTicksAndRejections (node:internal/process/task_queues:105:5)",
    "name": "Error"
  }
}
2025-10-13 01:08:13 [ERROR]: Uncaught Exception:
{
  "service": "task-management-api",
  "error": {
    "message": "listen EADDRINUSE: address already in use :::5000",
    "stack": "Error: listen EADDRINUSE: address already in use :::5000\n    at Server.setupListenHandle [as _listen2] (node:net:1939:16)\n    at listenInCluster (node:net:1996:12)\n    at Server.listen (node:net:2101:7)\n    at Function.listen (D:\\Task\\enterprise-task-management\\backend\\node_modules\\express\\lib\\application.js:635:24)\n    at App.start (D:\\Task\\enterprise-task-management\\backend\\src\\app.ts:251:16)\n    at processTicksAndRejections (node:internal/process/task_queues:105:5)",
    "name": "Error"
  }
}
2025-10-13 01:09:07 [ERROR]: Uncaught Exception:
{
  "service": "task-management-api",
  "error": {
    "message": "listen EADDRINUSE: address already in use :::5000",
    "stack": "Error: listen EADDRINUSE: address already in use :::5000\n    at Server.setupListenHandle [as _listen2] (node:net:1939:16)\n    at listenInCluster (node:net:1996:12)\n    at Server.listen (node:net:2101:7)\n    at Function.listen (D:\\Task\\enterprise-task-management\\backend\\node_modules\\express\\lib\\application.js:635:24)\n    at App.start (D:\\Task\\enterprise-task-management\\backend\\src\\app.ts:251:16)\n    at processTicksAndRejections (node:internal/process/task_queues:105:5)",
    "name": "Error"
  }
}
2025-10-13 01:09:07 [ERROR]: Uncaught Exception:
{
  "service": "task-management-api",
  "error": {
    "message": "listen EADDRINUSE: address already in use :::5000",
    "stack": "Error: listen EADDRINUSE: address already in use :::5000\n    at Server.setupListenHandle [as _listen2] (node:net:1939:16)\n    at listenInCluster (node:net:1996:12)\n    at Server.listen (node:net:2101:7)\n    at Function.listen (D:\\Task\\enterprise-task-management\\backend\\node_modules\\express\\lib\\application.js:635:24)\n    at App.start (D:\\Task\\enterprise-task-management\\backend\\src\\app.ts:251:16)\n    at processTicksAndRejections (node:internal/process/task_queues:105:5)",
    "name": "Error"
  }
}
2025-10-13 01:09:35 [ERROR]: Uncaught Exception:
{
  "service": "task-management-api",
  "error": {
    "message": "listen EADDRINUSE: address already in use :::5000",
    "stack": "Error: listen EADDRINUSE: address already in use :::5000\n    at Server.setupListenHandle [as _listen2] (node:net:1939:16)\n    at listenInCluster (node:net:1996:12)\n    at Server.listen (node:net:2101:7)\n    at Function.listen (D:\\Task\\enterprise-task-management\\backend\\node_modules\\express\\lib\\application.js:635:24)\n    at App.start (D:\\Task\\enterprise-task-management\\backend\\src\\app.ts:251:16)\n    at processTicksAndRejections (node:internal/process/task_queues:105:5)",
    "name": "Error"
  }
}
2025-10-13 01:09:35 [ERROR]: Uncaught Exception:
{
  "service": "task-management-api",
  "error": {
    "message": "listen EADDRINUSE: address already in use :::5000",
    "stack": "Error: listen EADDRINUSE: address already in use :::5000\n    at Server.setupListenHandle [as _listen2] (node:net:1939:16)\n    at listenInCluster (node:net:1996:12)\n    at Server.listen (node:net:2101:7)\n    at Function.listen (D:\\Task\\enterprise-task-management\\backend\\node_modules\\express\\lib\\application.js:635:24)\n    at App.start (D:\\Task\\enterprise-task-management\\backend\\src\\app.ts:251:16)\n    at processTicksAndRejections (node:internal/process/task_queues:105:5)",
    "name": "Error"
  }
}
2025-10-13 01:09:45 [ERROR]: Uncaught Exception:
{
  "service": "task-management-api",
  "error": {
    "message": "listen EADDRINUSE: address already in use :::5000",
    "stack": "Error: listen EADDRINUSE: address already in use :::5000\n    at Server.setupListenHandle [as _listen2] (node:net:1939:16)\n    at listenInCluster (node:net:1996:12)\n    at Server.listen (node:net:2101:7)\n    at Function.listen (D:\\Task\\enterprise-task-management\\backend\\node_modules\\express\\lib\\application.js:635:24)\n    at App.start (D:\\Task\\enterprise-task-management\\backend\\src\\app.ts:251:16)\n    at processTicksAndRejections (node:internal/process/task_queues:105:5)",
    "name": "Error"
  }
}
2025-10-13 01:10:53 [ERROR]: Uncaught Exception:
{
  "service": "task-management-api",
  "error": {
    "message": "listen EADDRINUSE: address already in use :::5000",
    "stack": "Error: listen EADDRINUSE: address already in use :::5000\n    at Server.setupListenHandle [as _listen2] (node:net:1939:16)\n    at listenInCluster (node:net:1996:12)\n    at Server.listen (node:net:2101:7)\n    at Function.listen (D:\\Task\\enterprise-task-management\\backend\\node_modules\\express\\lib\\application.js:635:24)\n    at App.start (D:\\Task\\enterprise-task-management\\backend\\src\\app.ts:251:16)\n    at processTicksAndRejections (node:internal/process/task_queues:105:5)",
    "name": "Error"
  }
}
2025-10-13 01:11:21 [ERROR]: Uncaught Exception:
{
  "service": "task-management-api",
  "error": {
    "message": "listen EADDRINUSE: address already in use :::5000",
    "stack": "Error: listen EADDRINUSE: address already in use :::5000\n    at Server.setupListenHandle [as _listen2] (node:net:1939:16)\n    at listenInCluster (node:net:1996:12)\n    at Server.listen (node:net:2101:7)\n    at Function.listen (D:\\Task\\enterprise-task-management\\backend\\node_modules\\express\\lib\\application.js:635:24)\n    at App.start (D:\\Task\\enterprise-task-management\\backend\\src\\app.ts:251:16)\n    at processTicksAndRejections (node:internal/process/task_queues:105:5)",
    "name": "Error"
  }
}
2025-10-13 01:11:22 [ERROR]: Uncaught Exception:
{
  "service": "task-management-api",
  "error": {
    "message": "listen EADDRINUSE: address already in use :::5000",
    "stack": "Error: listen EADDRINUSE: address already in use :::5000\n    at Server.setupListenHandle [as _listen2] (node:net:1939:16)\n    at listenInCluster (node:net:1996:12)\n    at Server.listen (node:net:2101:7)\n    at Function.listen (D:\\Task\\enterprise-task-management\\backend\\node_modules\\express\\lib\\application.js:635:24)\n    at App.start (D:\\Task\\enterprise-task-management\\backend\\src\\app.ts:251:16)\n    at processTicksAndRejections (node:internal/process/task_queues:105:5)",
    "name": "Error"
  }
}
2025-10-13 01:12:03 [ERROR]: Uncaught Exception:
{
  "service": "task-management-api",
  "error": {
    "message": "listen EADDRINUSE: address already in use :::5000",
    "stack": "Error: listen EADDRINUSE: address already in use :::5000\n    at Server.setupListenHandle [as _listen2] (node:net:1939:16)\n    at listenInCluster (node:net:1996:12)\n    at Server.listen (node:net:2101:7)\n    at Function.listen (D:\\Task\\enterprise-task-management\\backend\\node_modules\\express\\lib\\application.js:635:24)\n    at App.start (D:\\Task\\enterprise-task-management\\backend\\src\\app.ts:251:16)\n    at processTicksAndRejections (node:internal/process/task_queues:105:5)",
    "name": "Error"
  }
}
2025-10-13 01:12:03 [ERROR]: Uncaught Exception:
{
  "service": "task-management-api",
  "error": {
    "message": "listen EADDRINUSE: address already in use :::5000",
    "stack": "Error: listen EADDRINUSE: address already in use :::5000\n    at Server.setupListenHandle [as _listen2] (node:net:1939:16)\n    at listenInCluster (node:net:1996:12)\n    at Server.listen (node:net:2101:7)\n    at Function.listen (D:\\Task\\enterprise-task-management\\backend\\node_modules\\express\\lib\\application.js:635:24)\n    at App.start (D:\\Task\\enterprise-task-management\\backend\\src\\app.ts:251:16)\n    at processTicksAndRejections (node:internal/process/task_queues:105:5)",
    "name": "Error"
  }
}
2025-10-13 01:18:27 [ERROR]: Uncaught Exception:
{
  "service": "task-management-api",
  "error": {
    "message": "listen EADDRINUSE: address already in use :::5000",
    "stack": "Error: listen EADDRINUSE: address already in use :::5000\n    at Server.setupListenHandle [as _listen2] (node:net:1939:16)\n    at listenInCluster (node:net:1996:12)\n    at Server.listen (node:net:2101:7)\n    at Function.listen (D:\\Task\\enterprise-task-management\\backend\\node_modules\\express\\lib\\application.js:635:24)\n    at App.start (D:\\Task\\enterprise-task-management\\backend\\src\\app.ts:251:16)\n    at processTicksAndRejections (node:internal/process/task_queues:105:5)",
    "name": "Error"
  }
}
2025-10-13 01:18:27 [ERROR]: Uncaught Exception:
{
  "service": "task-management-api",
  "error": {
    "message": "listen EADDRINUSE: address already in use :::5000",
    "stack": "Error: listen EADDRINUSE: address already in use :::5000\n    at Server.setupListenHandle [as _listen2] (node:net:1939:16)\n    at listenInCluster (node:net:1996:12)\n    at Server.listen (node:net:2101:7)\n    at Function.listen (D:\\Task\\enterprise-task-management\\backend\\node_modules\\express\\lib\\application.js:635:24)\n    at App.start (D:\\Task\\enterprise-task-management\\backend\\src\\app.ts:251:16)\n    at processTicksAndRejections (node:internal/process/task_queues:105:5)",
    "name": "Error"
  }
}
2025-10-13 01:19:01 [ERROR]: Uncaught Exception:
{
  "service": "task-management-api",
  "error": {
    "message": "listen EADDRINUSE: address already in use :::5000",
    "stack": "Error: listen EADDRINUSE: address already in use :::5000\n    at Server.setupListenHandle [as _listen2] (node:net:1939:16)\n    at listenInCluster (node:net:1996:12)\n    at Server.listen (node:net:2101:7)\n    at Function.listen (D:\\Task\\enterprise-task-management\\backend\\node_modules\\express\\lib\\application.js:635:24)\n    at App.start (D:\\Task\\enterprise-task-management\\backend\\src\\app.ts:251:16)\n    at processTicksAndRejections (node:internal/process/task_queues:105:5)",
    "name": "Error"
  }
}
2025-10-13 01:19:01 [ERROR]: Uncaught Exception:
{
  "service": "task-management-api",
  "error": {
    "message": "listen EADDRINUSE: address already in use :::5000",
    "stack": "Error: listen EADDRINUSE: address already in use :::5000\n    at Server.setupListenHandle [as _listen2] (node:net:1939:16)\n    at listenInCluster (node:net:1996:12)\n    at Server.listen (node:net:2101:7)\n    at Function.listen (D:\\Task\\enterprise-task-management\\backend\\node_modules\\express\\lib\\application.js:635:24)\n    at App.start (D:\\Task\\enterprise-task-management\\backend\\src\\app.ts:251:16)\n    at processTicksAndRejections (node:internal/process/task_queues:105:5)",
    "name": "Error"
  }
}
2025-10-13 01:19:09 [ERROR]: Uncaught Exception:
{
  "service": "task-management-api",
  "error": {
    "message": "listen EADDRINUSE: address already in use :::5000",
    "stack": "Error: listen EADDRINUSE: address already in use :::5000\n    at Server.setupListenHandle [as _listen2] (node:net:1939:16)\n    at listenInCluster (node:net:1996:12)\n    at Server.listen (node:net:2101:7)\n    at Function.listen (D:\\Task\\enterprise-task-management\\backend\\node_modules\\express\\lib\\application.js:635:24)\n    at App.start (D:\\Task\\enterprise-task-management\\backend\\src\\app.ts:251:16)\n    at processTicksAndRejections (node:internal/process/task_queues:105:5)",
    "name": "Error"
  }
}
2025-10-13 01:19:09 [ERROR]: Uncaught Exception:
{
  "service": "task-management-api",
  "error": {
    "message": "listen EADDRINUSE: address already in use :::5000",
    "stack": "Error: listen EADDRINUSE: address already in use :::5000\n    at Server.setupListenHandle [as _listen2] (node:net:1939:16)\n    at listenInCluster (node:net:1996:12)\n    at Server.listen (node:net:2101:7)\n    at Function.listen (D:\\Task\\enterprise-task-management\\backend\\node_modules\\express\\lib\\application.js:635:24)\n    at App.start (D:\\Task\\enterprise-task-management\\backend\\src\\app.ts:251:16)\n    at processTicksAndRejections (node:internal/process/task_queues:105:5)",
    "name": "Error"
  }
}
2025-10-13 01:19:22 [ERROR]: Uncaught Exception:
{
  "service": "task-management-api",
  "error": {
    "message": "listen EADDRINUSE: address already in use :::5000",
    "stack": "Error: listen EADDRINUSE: address already in use :::5000\n    at Server.setupListenHandle [as _listen2] (node:net:1939:16)\n    at listenInCluster (node:net:1996:12)\n    at Server.listen (node:net:2101:7)\n    at Function.listen (D:\\Task\\enterprise-task-management\\backend\\node_modules\\express\\lib\\application.js:635:24)\n    at App.start (D:\\Task\\enterprise-task-management\\backend\\src\\app.ts:251:16)\n    at processTicksAndRejections (node:internal/process/task_queues:105:5)",
    "name": "Error"
  }
}
2025-10-13 01:19:22 [ERROR]: Uncaught Exception:
{
  "service": "task-management-api",
  "error": {
    "message": "listen EADDRINUSE: address already in use :::5000",
    "stack": "Error: listen EADDRINUSE: address already in use :::5000\n    at Server.setupListenHandle [as _listen2] (node:net:1939:16)\n    at listenInCluster (node:net:1996:12)\n    at Server.listen (node:net:2101:7)\n    at Function.listen (D:\\Task\\enterprise-task-management\\backend\\node_modules\\express\\lib\\application.js:635:24)\n    at App.start (D:\\Task\\enterprise-task-management\\backend\\src\\app.ts:251:16)\n    at processTicksAndRejections (node:internal/process/task_queues:105:5)",
    "name": "Error"
  }
}
2025-10-13 01:21:41 [ERROR]: Uncaught Exception:
{
  "service": "task-management-api",
  "error": {
    "message": "listen EADDRINUSE: address already in use :::5000",
    "stack": "Error: listen EADDRINUSE: address already in use :::5000\n    at Server.setupListenHandle [as _listen2] (node:net:1939:16)\n    at listenInCluster (node:net:1996:12)\n    at Server.listen (node:net:2101:7)\n    at Function.listen (D:\\Task\\enterprise-task-management\\backend\\node_modules\\express\\lib\\application.js:635:24)\n    at App.start (D:\\Task\\enterprise-task-management\\backend\\src\\app.ts:251:16)\n    at processTicksAndRejections (node:internal/process/task_queues:105:5)",
    "name": "Error"
  }
}
2025-10-13 01:21:41 [ERROR]: Uncaught Exception:
{
  "service": "task-management-api",
  "error": {
    "message": "listen EADDRINUSE: address already in use :::5000",
    "stack": "Error: listen EADDRINUSE: address already in use :::5000\n    at Server.setupListenHandle [as _listen2] (node:net:1939:16)\n    at listenInCluster (node:net:1996:12)\n    at Server.listen (node:net:2101:7)\n    at Function.listen (D:\\Task\\enterprise-task-management\\backend\\node_modules\\express\\lib\\application.js:635:24)\n    at App.start (D:\\Task\\enterprise-task-management\\backend\\src\\app.ts:251:16)\n    at processTicksAndRejections (node:internal/process/task_queues:105:5)",
    "name": "Error"
  }
}
2025-10-13 01:21:51 [ERROR]: Uncaught Exception:
{
  "service": "task-management-api",
  "error": {
    "message": "listen EADDRINUSE: address already in use :::5000",
    "stack": "Error: listen EADDRINUSE: address already in use :::5000\n    at Server.setupListenHandle [as _listen2] (node:net:1939:16)\n    at listenInCluster (node:net:1996:12)\n    at Server.listen (node:net:2101:7)\n    at Function.listen (D:\\Task\\enterprise-task-management\\backend\\node_modules\\express\\lib\\application.js:635:24)\n    at App.start (D:\\Task\\enterprise-task-management\\backend\\src\\app.ts:251:16)\n    at processTicksAndRejections (node:internal/process/task_queues:105:5)",
    "name": "Error"
  }
}
2025-10-13 01:21:51 [ERROR]: Uncaught Exception:
{
  "service": "task-management-api",
  "error": {
    "message": "listen EADDRINUSE: address already in use :::5000",
    "stack": "Error: listen EADDRINUSE: address already in use :::5000\n    at Server.setupListenHandle [as _listen2] (node:net:1939:16)\n    at listenInCluster (node:net:1996:12)\n    at Server.listen (node:net:2101:7)\n    at Function.listen (D:\\Task\\enterprise-task-management\\backend\\node_modules\\express\\lib\\application.js:635:24)\n    at App.start (D:\\Task\\enterprise-task-management\\backend\\src\\app.ts:251:16)\n    at processTicksAndRejections (node:internal/process/task_queues:105:5)",
    "name": "Error"
  }
}
2025-10-14 10:43:17 [ERROR]: Uncaught Exception:
{
  "service": "task-management-api",
  "error": {
    "message": "listen EADDRINUSE: address already in use :::5000",
    "stack": "Error: listen EADDRINUSE: address already in use :::5000\n    at Server.setupListenHandle [as _listen2] (node:net:1939:16)\n    at listenInCluster (node:net:1996:12)\n    at Server.listen (node:net:2101:7)\n    at Function.listen (D:\\Task\\enterprise-task-management\\backend\\node_modules\\express\\lib\\application.js:635:24)\n    at App.start (D:\\Task\\enterprise-task-management\\backend\\src\\app.ts:251:16)\n    at processTicksAndRejections (node:internal/process/task_queues:105:5)",
    "name": "Error"
  }
}
2025-10-14 10:44:49 [ERROR]: Uncaught Exception:
{
  "service": "task-management-api",
  "error": {
    "message": "listen EADDRINUSE: address already in use :::5000",
    "stack": "Error: listen EADDRINUSE: address already in use :::5000\n    at Server.setupListenHandle [as _listen2] (node:net:1939:16)\n    at listenInCluster (node:net:1996:12)\n    at Server.listen (node:net:2101:7)\n    at Function.listen (D:\\Task\\enterprise-task-management\\backend\\node_modules\\express\\lib\\application.js:635:24)\n    at App.start (D:\\Task\\enterprise-task-management\\backend\\src\\app.ts:251:16)\n    at processTicksAndRejections (node:internal/process/task_queues:105:5)",
    "name": "Error"
  }
}
2025-10-14 10:45:17 [ERROR]: Uncaught Exception:
{
  "service": "task-management-api",
  "error": {
    "message": "listen EADDRINUSE: address already in use :::5000",
    "stack": "Error: listen EADDRINUSE: address already in use :::5000\n    at Server.setupListenHandle [as _listen2] (node:net:1939:16)\n    at listenInCluster (node:net:1996:12)\n    at Server.listen (node:net:2101:7)\n    at Function.listen (D:\\Task\\enterprise-task-management\\backend\\node_modules\\express\\lib\\application.js:635:24)\n    at App.start (D:\\Task\\enterprise-task-management\\backend\\src\\app.ts:251:16)\n    at processTicksAndRejections (node:internal/process/task_queues:105:5)",
    "name": "Error"
  }
}
2025-10-14 10:45:30 [ERROR]: Uncaught Exception:
{
  "service": "task-management-api",
  "error": {
    "message": "listen EADDRINUSE: address already in use :::5000",
    "stack": "Error: listen EADDRINUSE: address already in use :::5000\n    at Server.setupListenHandle [as _listen2] (node:net:1939:16)\n    at listenInCluster (node:net:1996:12)\n    at Server.listen (node:net:2101:7)\n    at Function.listen (D:\\Task\\enterprise-task-management\\backend\\node_modules\\express\\lib\\application.js:635:24)\n    at App.start (D:\\Task\\enterprise-task-management\\backend\\src\\app.ts:251:16)\n    at processTicksAndRejections (node:internal/process/task_queues:105:5)",
    "name": "Error"
  }
}
2025-10-14 10:46:30 [ERROR]: Uncaught Exception:
{
  "service": "task-management-api",
  "error": {
    "message": "listen EADDRINUSE: address already in use :::5000",
    "stack": "Error: listen EADDRINUSE: address already in use :::5000\n    at Server.setupListenHandle [as _listen2] (node:net:1939:16)\n    at listenInCluster (node:net:1996:12)\n    at Server.listen (node:net:2101:7)\n    at Function.listen (D:\\Task\\enterprise-task-management\\backend\\node_modules\\express\\lib\\application.js:635:24)\n    at App.start (D:\\Task\\enterprise-task-management\\backend\\src\\app.ts:251:16)\n    at processTicksAndRejections (node:internal/process/task_queues:105:5)",
    "name": "Error"
  }
}
2025-10-14 10:49:24 [ERROR]: Uncaught Exception:
{
  "service": "task-management-api",
  "error": {
    "message": "listen EADDRINUSE: address already in use :::5000",
    "stack": "Error: listen EADDRINUSE: address already in use :::5000\n    at Server.setupListenHandle [as _listen2] (node:net:1939:16)\n    at listenInCluster (node:net:1996:12)\n    at Server.listen (node:net:2101:7)\n    at Function.listen (D:\\Task\\enterprise-task-management\\backend\\node_modules\\express\\lib\\application.js:635:24)\n    at App.start (D:\\Task\\enterprise-task-management\\backend\\src\\app.ts:251:16)\n    at processTicksAndRejections (node:internal/process/task_queues:105:5)",
    "name": "Error"
  }
}
2025-10-14 10:51:54 [ERROR]: Uncaught Exception:
{
  "service": "task-management-api",
  "error": {
    "message": "listen EADDRINUSE: address already in use :::5000",
    "stack": "Error: listen EADDRINUSE: address already in use :::5000\n    at Server.setupListenHandle [as _listen2] (node:net:1939:16)\n    at listenInCluster (node:net:1996:12)\n    at Server.listen (node:net:2101:7)\n    at Function.listen (D:\\Task\\enterprise-task-management\\backend\\node_modules\\express\\lib\\application.js:635:24)\n    at App.start (D:\\Task\\enterprise-task-management\\backend\\src\\app.ts:251:16)\n    at processTicksAndRejections (node:internal/process/task_queues:105:5)",
    "name": "Error"
  }
}
2025-10-14 10:53:35 [ERROR]: Uncaught Exception:
{
  "service": "task-management-api",
  "error": {
    "message": "listen EADDRINUSE: address already in use :::5000",
    "stack": "Error: listen EADDRINUSE: address already in use :::5000\n    at Server.setupListenHandle [as _listen2] (node:net:1939:16)\n    at listenInCluster (node:net:1996:12)\n    at Server.listen (node:net:2101:7)\n    at Function.listen (D:\\Task\\enterprise-task-management\\backend\\node_modules\\express\\lib\\application.js:635:24)\n    at App.start (D:\\Task\\enterprise-task-management\\backend\\src\\app.ts:251:16)\n    at processTicksAndRejections (node:internal/process/task_queues:105:5)",
    "name": "Error"
  }
}
2025-10-14 10:53:49 [ERROR]: Uncaught Exception:
{
  "service": "task-management-api",
  "error": {
    "message": "listen EADDRINUSE: address already in use :::5000",
    "stack": "Error: listen EADDRINUSE: address already in use :::5000\n    at Server.setupListenHandle [as _listen2] (node:net:1939:16)\n    at listenInCluster (node:net:1996:12)\n    at Server.listen (node:net:2101:7)\n    at Function.listen (D:\\Task\\enterprise-task-management\\backend\\node_modules\\express\\lib\\application.js:635:24)\n    at App.start (D:\\Task\\enterprise-task-management\\backend\\src\\app.ts:251:16)\n    at processTicksAndRejections (node:internal/process/task_queues:105:5)",
    "name": "Error"
  }
}
2025-10-14 10:54:20 [ERROR]: Uncaught Exception:
{
  "service": "task-management-api",
  "error": {
    "message": "listen EADDRINUSE: address already in use :::5000",
    "stack": "Error: listen EADDRINUSE: address already in use :::5000\n    at Server.setupListenHandle [as _listen2] (node:net:1939:16)\n    at listenInCluster (node:net:1996:12)\n    at Server.listen (node:net:2101:7)\n    at Function.listen (D:\\Task\\enterprise-task-management\\backend\\node_modules\\express\\lib\\application.js:635:24)\n    at App.start (D:\\Task\\enterprise-task-management\\backend\\src\\app.ts:251:16)\n    at processTicksAndRejections (node:internal/process/task_queues:105:5)",
    "name": "Error"
  }
}
2025-10-14 10:54:24 [ERROR]: Uncaught Exception:
{
  "service": "task-management-api",
  "error": {
    "message": "listen EADDRINUSE: address already in use :::5000",
    "stack": "Error: listen EADDRINUSE: address already in use :::5000\n    at Server.setupListenHandle [as _listen2] (node:net:1939:16)\n    at listenInCluster (node:net:1996:12)\n    at Server.listen (node:net:2101:7)\n    at Function.listen (D:\\Task\\enterprise-task-management\\backend\\node_modules\\express\\lib\\application.js:635:24)\n    at App.start (D:\\Task\\enterprise-task-management\\backend\\src\\app.ts:251:16)\n    at processTicksAndRejections (node:internal/process/task_queues:105:5)",
    "name": "Error"
  }
}
2025-10-14 10:54:28 [ERROR]: Uncaught Exception:
{
  "service": "task-management-api",
  "error": {
    "message": "listen EADDRINUSE: address already in use :::5000",
    "stack": "Error: listen EADDRINUSE: address already in use :::5000\n    at Server.setupListenHandle [as _listen2] (node:net:1939:16)\n    at listenInCluster (node:net:1996:12)\n    at Server.listen (node:net:2101:7)\n    at Function.listen (D:\\Task\\enterprise-task-management\\backend\\node_modules\\express\\lib\\application.js:635:24)\n    at App.start (D:\\Task\\enterprise-task-management\\backend\\src\\app.ts:251:16)\n    at processTicksAndRejections (node:internal/process/task_queues:105:5)",
    "name": "Error"
  }
}
2025-10-14 10:54:30 [ERROR]: Uncaught Exception:
{
  "service": "task-management-api",
  "error": {
    "message": "listen EADDRINUSE: address already in use :::5000",
    "stack": "Error: listen EADDRINUSE: address already in use :::5000\n    at Server.setupListenHandle [as _listen2] (node:net:1939:16)\n    at listenInCluster (node:net:1996:12)\n    at Server.listen (node:net:2101:7)\n    at Function.listen (D:\\Task\\enterprise-task-management\\backend\\node_modules\\express\\lib\\application.js:635:24)\n    at App.start (D:\\Task\\enterprise-task-management\\backend\\src\\app.ts:251:16)\n    at processTicksAndRejections (node:internal/process/task_queues:105:5)",
    "name": "Error"
  }
}
2025-10-14 10:54:42 [ERROR]: Uncaught Exception:
{
  "service": "task-management-api",
  "error": {
    "message": "listen EADDRINUSE: address already in use :::5000",
    "stack": "Error: listen EADDRINUSE: address already in use :::5000\n    at Server.setupListenHandle [as _listen2] (node:net:1939:16)\n    at listenInCluster (node:net:1996:12)\n    at Server.listen (node:net:2101:7)\n    at Function.listen (D:\\Task\\enterprise-task-management\\backend\\node_modules\\express\\lib\\application.js:635:24)\n    at App.start (D:\\Task\\enterprise-task-management\\backend\\src\\app.ts:251:16)\n    at processTicksAndRejections (node:internal/process/task_queues:105:5)",
    "name": "Error"
  }
}
2025-10-14 10:54:52 [ERROR]: Uncaught Exception:
{
  "service": "task-management-api",
  "error": {
    "message": "listen EADDRINUSE: address already in use :::5000",
    "stack": "Error: listen EADDRINUSE: address already in use :::5000\n    at Server.setupListenHandle [as _listen2] (node:net:1939:16)\n    at listenInCluster (node:net:1996:12)\n    at Server.listen (node:net:2101:7)\n    at Function.listen (D:\\Task\\enterprise-task-management\\backend\\node_modules\\express\\lib\\application.js:635:24)\n    at App.start (D:\\Task\\enterprise-task-management\\backend\\src\\app.ts:251:16)\n    at processTicksAndRejections (node:internal/process/task_queues:105:5)",
    "name": "Error"
  }
}
2025-10-14 10:55:02 [ERROR]: Uncaught Exception:
{
  "service": "task-management-api",
  "error": {
    "message": "listen EADDRINUSE: address already in use :::5000",
    "stack": "Error: listen EADDRINUSE: address already in use :::5000\n    at Server.setupListenHandle [as _listen2] (node:net:1939:16)\n    at listenInCluster (node:net:1996:12)\n    at Server.listen (node:net:2101:7)\n    at Function.listen (D:\\Task\\enterprise-task-management\\backend\\node_modules\\express\\lib\\application.js:635:24)\n    at App.start (D:\\Task\\enterprise-task-management\\backend\\src\\app.ts:251:16)\n    at processTicksAndRejections (node:internal/process/task_queues:105:5)",
    "name": "Error"
  }
}
2025-10-14 10:55:11 [ERROR]: Uncaught Exception:
{
  "service": "task-management-api",
  "error": {
    "message": "listen EADDRINUSE: address already in use :::5000",
    "stack": "Error: listen EADDRINUSE: address already in use :::5000\n    at Server.setupListenHandle [as _listen2] (node:net:1939:16)\n    at listenInCluster (node:net:1996:12)\n    at Server.listen (node:net:2101:7)\n    at Function.listen (D:\\Task\\enterprise-task-management\\backend\\node_modules\\express\\lib\\application.js:635:24)\n    at App.start (D:\\Task\\enterprise-task-management\\backend\\src\\app.ts:251:16)\n    at processTicksAndRejections (node:internal/process/task_queues:105:5)",
    "name": "Error"
  }
}
2025-10-14 10:55:20 [ERROR]: Uncaught Exception:
{
  "service": "task-management-api",
  "error": {
    "message": "listen EADDRINUSE: address already in use :::5000",
    "stack": "Error: listen EADDRINUSE: address already in use :::5000\n    at Server.setupListenHandle [as _listen2] (node:net:1939:16)\n    at listenInCluster (node:net:1996:12)\n    at Server.listen (node:net:2101:7)\n    at Function.listen (D:\\Task\\enterprise-task-management\\backend\\node_modules\\express\\lib\\application.js:635:24)\n    at App.start (D:\\Task\\enterprise-task-management\\backend\\src\\app.ts:251:16)\n    at processTicksAndRejections (node:internal/process/task_queues:105:5)",
    "name": "Error"
  }
}
2025-10-14 10:55:44 [ERROR]: Uncaught Exception:
{
  "service": "task-management-api",
  "error": {
    "message": "listen EADDRINUSE: address already in use :::5000",
    "stack": "Error: listen EADDRINUSE: address already in use :::5000\n    at Server.setupListenHandle [as _listen2] (node:net:1939:16)\n    at listenInCluster (node:net:1996:12)\n    at Server.listen (node:net:2101:7)\n    at Function.listen (D:\\Task\\enterprise-task-management\\backend\\node_modules\\express\\lib\\application.js:635:24)\n    at App.start (D:\\Task\\enterprise-task-management\\backend\\src\\app.ts:251:16)\n    at processTicksAndRejections (node:internal/process/task_queues:105:5)",
    "name": "Error"
  }
}
2025-10-14 11:01:32 [ERROR]: Uncaught Exception:
{
  "service": "task-management-api",
  "error": {
    "message": "listen EADDRINUSE: address already in use :::5000",
    "stack": "Error: listen EADDRINUSE: address already in use :::5000\n    at Server.setupListenHandle [as _listen2] (node:net:1939:16)\n    at listenInCluster (node:net:1996:12)\n    at Server.listen (node:net:2101:7)\n    at Function.listen (D:\\Task\\enterprise-task-management\\backend\\node_modules\\express\\lib\\application.js:635:24)\n    at App.start (D:\\Task\\enterprise-task-management\\backend\\src\\app.ts:258:16)\n    at processTicksAndRejections (node:internal/process/task_queues:105:5)",
    "name": "Error"
  }
}
2025-10-14 14:02:11 [ERROR]: Uncaught Exception:
{
  "service": "task-management-api",
  "error": {
    "message": "listen EADDRINUSE: address already in use :::5000",
    "stack": "Error: listen EADDRINUSE: address already in use :::5000\n    at Server.setupListenHandle [as _listen2] (node:net:1939:16)\n    at listenInCluster (node:net:1996:12)\n    at Server.listen (node:net:2101:7)\n    at Function.listen (D:\\Task\\enterprise-task-management\\backend\\node_modules\\express\\lib\\application.js:635:24)\n    at App.start (D:\\Task\\enterprise-task-management\\backend\\src\\app.ts:261:16)\n    at processTicksAndRejections (node:internal/process/task_queues:105:5)",
    "name": "Error"
  }
}
2025-10-14 14:33:01 [ERROR]: Uncaught Exception:
{
  "service": "task-management-api",
  "error": {
    "message": "listen EADDRINUSE: address already in use :::5000",
    "stack": "Error: listen EADDRINUSE: address already in use :::5000\n    at Server.setupListenHandle [as _listen2] (node:net:1939:16)\n    at listenInCluster (node:net:1996:12)\n    at Server.listen (node:net:2101:7)\n    at Function.listen (D:\\Task\\enterprise-task-management\\backend\\node_modules\\express\\lib\\application.js:635:24)\n    at App.start (D:\\Task\\enterprise-task-management\\backend\\src\\app.ts:261:16)\n    at processTicksAndRejections (node:internal/process/task_queues:105:5)",
    "name": "Error"
  }
}
2025-10-14 14:37:18 [ERROR]: Uncaught Exception:
{
  "service": "task-management-api",
  "error": {
    "message": "listen EADDRINUSE: address already in use :::5000",
    "stack": "Error: listen EADDRINUSE: address already in use :::5000\n    at Server.setupListenHandle [as _listen2] (node:net:1939:16)\n    at listenInCluster (node:net:1996:12)\n    at Server.listen (node:net:2101:7)\n    at Function.listen (D:\\Task\\enterprise-task-management\\backend\\node_modules\\express\\lib\\application.js:635:24)\n    at App.start (D:\\Task\\enterprise-task-management\\backend\\src\\app.ts:261:16)\n    at processTicksAndRejections (node:internal/process/task_queues:105:5)",
    "name": "Error"
  }
}
2025-10-14 19:04:14 [ERROR]: Uncaught Exception:
{
  "service": "task-management-api",
  "error": {
    "message": "listen EADDRINUSE: address already in use :::5000",
    "stack": "Error: listen EADDRINUSE: address already in use :::5000\n    at Server.setupListenHandle [as _listen2] (node:net:1939:16)\n    at listenInCluster (node:net:1996:12)\n    at Server.listen (node:net:2101:7)\n    at Function.listen (D:\\Task\\enterprise-task-management\\backend\\node_modules\\express\\lib\\application.js:635:24)\n    at App.start (D:\\Task\\enterprise-task-management\\backend\\src\\app.ts:261:16)\n    at processTicksAndRejections (node:internal/process/task_queues:105:5)",
    "name": "Error"
  }
}
2025-10-15 10:25:47 [ERROR]: Uncaught Exception:
{
  "service": "task-management-api",
  "error": {
    "message": "listen EADDRINUSE: address already in use :::5000",
    "stack": "Error: listen EADDRINUSE: address already in use :::5000\n    at Server.setupListenHandle [as _listen2] (node:net:1939:16)\n    at listenInCluster (node:net:1996:12)\n    at Server.listen (node:net:2101:7)\n    at Function.listen (D:\\Task\\enterprise-task-management\\backend\\node_modules\\express\\lib\\application.js:635:24)\n    at App.start (D:\\Task\\enterprise-task-management\\backend\\src\\app.ts:250:16)\n    at processTicksAndRejections (node:internal/process/task_queues:105:5)",
    "name": "Error"
  }
}
